spring.application.name=msvc_cursos

# Configuración del servidor
server.port=${SERVER_PORT:8002}

# Configuración de la base de datos PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres2:5432/msvc-cursos}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgress}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.esteban.springboot.springmvc.app.msvc_cursos=INFO

# Configuracion de microservicio de usuarios
msvc.usuarios.url=${MSVC_USUARIOS_URL:msvc-usuarios:8001/usuarios}
